sudo: required
dist: trusty
language: python
python:
- '2.7'
# git submodules workaround
git:
  submodules: false
env:
- PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1'
services:
- redis-server
addons:
  postgresql: "9.3"
install:
- git clone --recursive https://github.com/PyBossa/pybossa.git
- sudo apt-get update -y && sudo apt-get install -y swig libffi-dev dbus libdbus-1-dev libdbus-glib-1-dev
- cd pybossa/
- pip install -U pip
- pip install -r requirements.txt
- cd ..
- cp -r random_scheduler/ pybossa/pybossa/plugins/
before_script:
- redis-server --version
- redis-server pybossa/contrib/redis/sentinel.conf --sentinel
- psql -c "create user rtester with createdb login password 'rtester'" -U postgres
- psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
script:
- nosetests test/ pybossa/test/
